#!/usr/bin/env node

import { execSync } from 'child_process'
import { program } from 'commander'
import { randomBytes } from 'crypto'
import enquirer from 'enquirer'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

interface Response {
  projectName: string
  description: string
  template: string
  git: string
}

/**
 * Local build and install output that must never reach a new project, even
 * when the CLI runs from a checkout where a template was built or installed.
 */
const SKIPPED_TEMPLATE_PATHS = new Set([
  'node_modules',
  '.next',
  '.swc',
  'out',
  'build',
  '.env',
  'next-env.d.ts',
  // Generated by the Workflow SDK on every build
  path.join('src', 'app', '.well-known')
])

/** Template files whose `{{PROJECT_NAME}}` and `{{PROJECT_DESCRIPTION}}` get filled in. */
const PLACEHOLDER_FILES = ['README.md', 'AGENTS.md']

const detectPackageManager = () => {
  const userAgent = process.env.npm_config_user_agent

  if (userAgent) {
    if (userAgent.startsWith('pnpm')) return 'pnpm'
    if (userAgent.startsWith('yarn')) return 'yarn'
    if (userAgent.startsWith('bun')) return 'bun'
  }

  return 'npm'
}

const getInstallCommand = (packageManager: string) => {
  switch (packageManager) {
    case 'pnpm':
      return 'pnpm i'
    case 'yarn':
      return 'yarn'
    case 'bun':
      return 'bun i'
    default:
      return 'npm i'
  }
}

const getRunCommand = (packageManager: string, script: string) =>
  packageManager === 'npm'
    ? `npm run ${script}`
    : `${packageManager} run ${script}`

program.action(async () => {
  const response: Response = await enquirer.prompt([
    {
      type: 'input',
      name: 'projectName',
      message: 'Enter the project name:',
      initial: 'my-project',
      // The name becomes a directory and the package.json name, so keep it
      // to characters that are safe for both.
      validate: (value: string) =>
        /^[a-z0-9][a-z0-9._-]{0,213}$/.test(value) ||
        'Use lowercase letters, numbers, dots, hyphens, and underscores.'
    },
    {
      type: 'input',
      name: 'description',
      message: 'Enter a description for the project:',
      initial: 'A Legendary Project'
    },
    {
      type: 'select',
      name: 'template',
      message: 'Select a template:',
      choices: [
        {
          name: 'nextjs',
          message:
            'Full-stack Next.js 16 app with Better Auth, an admin panel, shadcn/ui, and Drizzle'
        },
        {
          name: 'saas-starter',
          message:
            'SaaS starter with organizations, Stripe, support tickets, Better Auth, shadcn/ui, and Drizzle'
        },
        {
          name: 'api',
          message: 'API server with Elysia, Drizzle, and TypeScript'
        }
      ]
    },
    {
      type: 'select',
      name: 'git',
      message: 'Initialize a git repository?',
      choices: ['yes', 'no']
    }
  ])

  const { projectName, description, template, git } = response

  const projectDir = path.join(process.cwd(), projectName)

  if (fs.existsSync(projectDir)) {
    console.error(
      `Directory '${projectName}' already exists. Choose another project name or remove the directory.`
    )
    process.exit(1)
  }

  fs.mkdirSync(projectDir)

  const templateDir = path.join(__dirname, 'template', template)
  fs.cpSync(templateDir, projectDir, {
    recursive: true,
    filter: source => {
      const relative = path.relative(templateDir, source)
      return (
        !SKIPPED_TEMPLATE_PATHS.has(relative) &&
        !relative.split(path.sep).includes('node_modules') &&
        !relative.endsWith('.tsbuildinfo')
      )
    }
  })

  const renameGitignore = (dir: string) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const fullPath = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        renameGitignore(fullPath)
      } else if (entry.name === 'gitignore') {
        fs.renameSync(fullPath, path.join(dir, '.gitignore'))
      }
    }
  }
  renameGitignore(projectDir)

  const packageJsonFile = path.join(projectDir, 'package.json')
  const packageJson = JSON.parse(fs.readFileSync(packageJsonFile, 'utf-8'))
  packageJson.name = projectName
  packageJson.description = description
  fs.writeFileSync(packageJsonFile, `${JSON.stringify(packageJson, null, 2)}\n`)

  // Better Auth warns about weak secrets, so every project gets a random one.
  const envExampleFile = path.join(projectDir, '.env.example')
  const envExample = fs.readFileSync(envExampleFile, 'utf-8')
  fs.writeFileSync(
    path.join(projectDir, '.env'),
    envExample.replace(
      /^BETTER_AUTH_SECRET=.*$/m,
      `BETTER_AUTH_SECRET="${randomBytes(32).toString('base64')}"`
    )
  )

  for (const file of PLACEHOLDER_FILES) {
    const filePath = path.join(projectDir, file)
    if (!fs.existsSync(filePath)) continue
    fs.writeFileSync(
      filePath,
      fs
        .readFileSync(filePath, 'utf-8')
        .replaceAll('{{PROJECT_NAME}}', projectName)
        .replaceAll('{{PROJECT_DESCRIPTION}}', description)
    )
  }

  const readmeFile = path.join(projectDir, 'README.md')
  if (!fs.existsSync(readmeFile)) {
    fs.writeFileSync(readmeFile, `# ${projectName}\n\n${description}\n`)
  }

  if (git === 'yes') {
    try {
      execSync('git init', { cwd: projectDir, stdio: 'inherit' })
    } catch (err) {
      console.error('Error initializing git repository:', err)
    }
  }

  const pm = detectPackageManager()
  const installCommand = getInstallCommand(pm)
  const devCommand = getRunCommand(pm, 'dev')
  const dbPushCommand = getRunCommand(pm, 'db:push')

  console.log(
    `
Created a new app called '${projectName}' 🎉

To open the project in VS Code, run:

code ${projectName}


To get started, run these commands:
cd ${projectName}

${installCommand}

Fill in the values in .env, then create the database tables:

${dbPushCommand}

${devCommand}

Happy coding! 🚀
`
  )
})

program.parse(process.argv)
