import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'
import { defineConfig, globalIgnores } from 'eslint/config'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    'node_modules/**',
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // workflow-sdk autogenerated files
    'src/app/.well-known/**'
  ]),
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'off'
    }
  }
])

export default eslintConfig
